### ISSUE TITLE
Multi switch

### ISSUE THREAD

**Issue by MacGyver1rjq104** [markus-li/Hubitat#16]
I just got my Hubitat yesterday and worked all day today trying to set it up.  In Smartthings, I was able to use the Tasmota-connect (tasmota-hubitat-8.1.0.bin) on my wemos D1 mini boards.  I used hongtat device drivers and app he made for smartthings and I was able to get smartthings to see both switches.  In Hubitat, I can't figure out what driver and app I need for it to see two switches.  For example, I have one switch that uses GPIO5 - relay 1, GPIO12-Relay2 and a couple of other pins for my buttons to manually turn on the lights.  So My issue is when I find this in Habitat, it only sees the one switch (relay).  What am I missing?  I thought Hubitat was going to be easier than smartthings.  I appreciate any help you can give me.

**Comment by markus-li** [comment]
This is not really an issue as such, use the community thread for things like this. The issue tracking is for bugs and feature requests.

**Comment by MacGyver1rjq104** [comment]
> This is not really an issue as such, use the community thread for things like this. The issue tracking is for bugs and feature requests.

Can you help me find the proper place?  I am new to forums and this lucky I figured out to get this far... LOL

**Comment by markus-li** [comment]
Sure, you can find the release thread from today here:
[Community release thread](https://community.hubitat.com/t/release-tasmota-for-he-auto-detecting-tasmota-drivers-tasmota-firmware-7-x-8-x-for-he-for-use-with-tuya-sonoff-and-other-esp-devices/39322)
