### ISSUE TITLE
button function

### ISSUE THREAD

**Issue by MacGyver1rjq104** [markus-li/Hubitat#17]
When I set up a Sonoff basic or a wemo d1 mini and have a button switch to turn on the lights, it's is very intermittent.   Tasmota itself has the same issue I think.  Any suggestions?

**Comment by markus-li** [comment]
These are not Issues and does not belong here, go to the community:
https://community.hubitat.com

Describe more in detail what you have connected as well as paste the template and write a post in the community. For this type of problem I'd say write a new post and add @markus to it so I get a notification.
