### ISSUE TITLE
Looks like zigbee-xiaomi-aqara-plug-outlet-expanded works with ZNCZ04LM too, but I see one warn in logs

### ISSUE THREAD

**Issue by onixcv** [markus-li/Hubitat#22]
Unhandled Event PLEASE REPORT TO DEV - description:read attr - raw: A59101FCC082F700413D64100103282098390000000095398D2E0E40963900800945973900000000052104009A20100821160107270000000000000000092105060B20009B1001, dni: A591, endpoint: 01, cluster: FCC0, size: 82, attrId: 00F7, encoding: 41, command: 0A, value: 3D64100103282098390000000095398D2E0E40963900800945973900000000052104009A20100821160107270000000000000000092105060B20009B1001 | msgMap:[raw:A59101FCC082F700413D64100103282098390000000095398D2E0E40963900800945973900000000052104009A20100821160107270000000000000000092105060B20009B1001, dni:A591, endpoint:01, cluster:FCC0, size:82, attrId:00F7, encoding:41, command:0A, value:64100103282098390000000095398D2E0E40963900800945973900000000052104009A20100821160107270000000000000000092105060B20009B1001, clusterInt:64704, attrInt:247]

**Comment by ibezkrovnyi** [comment]
I have the same wall plug (ZNCZ04LM), and can confirm that zigbee-xiaomi-aqara-plug-outlet-expanded.groovy works with it. In the logs I can see the same Unhandled event:

```
warn Unhandled Event PLEASE REPORT TO DEV - description:read attr - raw: 896A01FCC082F700413D6410000328179839000000009539B528033E963900001645973900000000052101009A20100821160107270000000000000000092101020B20009B1001, dni: 8921, endpoint: 01, cluster: FCC0, size: 82, attrId: 00F7, encoding: 41, command: 0A, value: 3D6410000328179839000000009539B528033E963900001645973900000000052101009A20100821160107270000000000000000092101020B20009B1001 | msgMap:[raw:892101FCC082F700413D6410000328179839000000009539B528033E963900001645973900000000052101009A20100821160107270000000000000000092101020B20009B1001, dni:8921, endpoint:01, cluster:FCC0, size:82, attrId:00F7, encoding:41, command:0A, value:6410000328179839000000009539B528033E963900001645973900000000052101009A20100821160107270000000000000000092101020B20009B1001, clusterInt:64704, attrInt:247]
```
Event appears in the logs every 1-7 minutes (random interval between events).
