### ISSUE TITLE
Fix for contact functionality in Aqara Vibration Sensor

### ISSUE THREAD

**Issue by ernie** [markus-li/Hubitat#24]
Heya Markus. Since I don't have a way to submit a proper PR (as you rightly pointed out the last time) thought an issue might be better.

It looks like the attempt to implicitly cast String to BigDecimal fails in the Aqara Vibration Sensor driver. The fix is to explicitly create BigDecimals:

```groovy
void setClosedPosition() {
    BigDecimal cX = new BigDecimal(device.currentState("currentX")?.value)
    if(cX != null) {
        state.closedX = cX
        BigDecimal cY = new BigDecimal(device.currentState("currentY")?.value)
        state.closedY = cY
        BigDecimal cZ = new BigDecimal(device.currentState("currentZ")?.value)
        state.closedZ = cZ
        sendPositionEvent("closed")
        logging("Closed position set to $cX$DEGREE, $cY$DEGREE, $cZ$DEGREE", 100)
    } else {
        logging("Closed position NOT set because no 3-axis accelerometer reports have been received yet", 100)
    }
}

void setOpenPosition() {
    BigDecimal cX = new BigDecimal(device.currentState("currentX")?.value)
    if(cX != null) {
        state.openX = cX
        BigDecimal cY = new BigDecimal(device.currentState("currentY")?.value)
        state.openY = cY
        BigDecimal cZ = new BigDecimal(device.currentState("currentZ")?.value)
        state.openZ = cZ
        sendPositionEvent("open")
        logging("Open position set to $cX$DEGREE, $cY$DEGREE, $cZ$DEGREE", 100)
    } else {
        logging("Open position NOT set because no 3-axis accelerometer reports have been received yet", 100)
    }
}
```

**Comment by xcguy** [comment]
Definitely needs to be fixed otherwise the open/close functionality is broken.    My only concern is the casting of the currentValueX value which could result in null, which BigDecimal would choke on (runtime exception).   My suggested change:

`void setClosedPosition() {
    if (device.currentState("currentX")?.value != null) {
        BigDecimal cX = new BigDecimal(device.currentState("currentX")?.value)
        state.closedX = cX
        BigDecimal cY = new BigDecimal(device.currentState("currentY")?.value)
        state.closedY = cY
        BigDecimal cZ = new BigDecimal(device.currentState("currentZ")?.value)
        state.closedZ = cZ
        sendPositionEvent("closed")
        logging("Closed position set to $cX$DEGREE, $cY$DEGREE, $cZ$DEGREE", 100)
    } else {
        logging("Closed position NOT set because no 3-axis accelerometer reports have been received yet", 100)
    }
}

void setOpenPosition() {
    if (device.currentState("currentX")?.value != null) {
        BigDecimal cX = new BigDecimal(device.currentState("currentX")?.value)
        state.openX = cX
        BigDecimal cY = new BigDecimal(device.currentState("currentY")?.value)
        state.openY = cY
        BigDecimal cZ = new BigDecimal(device.currentState("currentZ")?.value)
        state.openZ = cZ 
        sendPositionEvent("open")
        logging("Open position set to $cX$DEGREE, $cY$DEGREE, $cZ$DEGREE", 100)
    } else {
        logging("Open position NOT set because no 3-axis accelerometer reports have been received yet", 100)
    }
}
`
