### ISSUE TITLE
Improve navigation during Autodetect\driver install

### ISSUE THREAD

**Issue by GaryMilne** [markus-li/Hubitat#4]
"Markus, I just tried out the AutoDiscover feature. It worked in that it found the 5 unassigned devices that I had. But I was surprised that after I had installed my first device that it did not lead me back to the other 4 devices in the AutoDiscover list. Meaning I would have to repeat the AutoDiscover process for each single device I installed.

If someone has been able to convert a device to Tasmota then they almost certainly know it's IP address. To me the primary advantage of AutoDiscover (I thought) would have been adding multiple devices in one run through."

**Solution**
I think in the screenshot to the right having two options.
Next Device and Quit AutoDiscovery or something like that.

**Comment by markus-li** [comment]
This is potentially implemented in the [latest commit](https://github.com/markus-li/Hubitat/commit/d8aecf0d659a38c900bb4bdc5ddc404e22b91a6a). Please test it.
